name: Comment on PR with Changed Folders and Links

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Changed Folders
        id: list-changed-folders
        run: |
          changed_folders=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep '^packages/' | cut -d/ -f2 | sort -u)
          echo "::set-output name=changed_folders::$changed_folders"

      - name: Generate Links
        id: generate-links
        run: |
          links=""
          for folder in ${{ steps.list-changed-folders.outputs.changed_folders }}; do
            branch_name=$(git rev-parse --abbrev-ref HEAD | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
            link="https://fwdays-mfe-showcase-${folder}-git-${branch_name}-vlad-kampov-s-team.vercel.app"
            links="${links}\n\"@kampov/${folder}\": \"${link}/kampov-${folder}.js\","
          done
          echo "::set-output name=links::$links"

      - name: Generate JSON
        id: generate-json
        run: |
          echo "{\"bundles\": {${{ steps.generate-links.outputs.links }} }}" > bundles.json
